export default [
  {
    Leaders: [
      {
        Name: "Fawwaz Bin Tasneem",
        Post: "Captain",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Mohammed Areeb Siddiqui",
        Post: "Vice-Captain",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Mohd Athar Zaid",
        Post: "Team Manager",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
    ],
  },
  {
    TechnicalMembers: [
      {
        Name: "Fawwaz Bin Tasneem",
        Post: "High Voltage Systems",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Mohammad Areeb Siddiqui",
        Post: "Power Train",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Mohammad Arham",
        Post: "Power Train",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Shazia Wali",
        Post: "Cooling",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Sana Farooqui",
        Post: "Cooling",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Zaki Abbas Zaidi",
        Post: "Low Voltage System",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Yashra Malik",
        Post: "High Voltage System",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Mohammad Ayman",
        Post: "Power Train",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
    ],
  },
  {
    ManagementMmebrs: [
      {
        Name: "Mohammad Athar Zaid",
        Post: "Management",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Mohd Haris Anwar",
        Post: "Management",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Abdul Hadi Zeeshan",
        Post: "Management",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Affan Khan",
        Post: "Management",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Mohammad Athar",
        Post: "Management",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
    ],
  },
];
